// Audio utility for UI sound effects
class AudioManager {
    constructor() {
        this.sounds = {};
        this.enabled = true;
        this.volume = 0.3; // Default volume
    }

    // Create audio context and generate sounds
    init() {
        // Create simple click sound using Web Audio API
        this.createClickSound();
    }

    createClickSound() {
        // We'll use a simple beep sound generated by Web Audio API
        this.sounds.click = () => {
            if (!this.enabled) return;

            try {
                const audioContext = new (window.AudioContext || window.webkitAudioContext)();
                const oscillator = audioContext.createOscillator();
                const gainNode = audioContext.createGain();

                oscillator.connect(gainNode);
                gainNode.connect(audioContext.destination);

                // Soft, pleasant click sound
                oscillator.frequency.value = 800;
                oscillator.type = 'sine';

                gainNode.gain.setValueAtTime(this.volume, audioContext.currentTime);
                gainNode.gain.exponentialRampToValueAtTime(0.01, audioContext.currentTime + 0.1);

                oscillator.start(audioContext.currentTime);
                oscillator.stop(audioContext.currentTime + 0.1);
            } catch (error) {
                console.warn('Audio playback failed:', error);
            }
        };
    }

    play(soundName) {
        if (this.sounds[soundName]) {
            this.sounds[soundName]();
        }
    }

    toggle() {
        this.enabled = !this.enabled;
        return this.enabled;
    }

    setVolume(vol) {
        this.volume = Math.max(0, Math.min(1, vol));
    }
}

// Create singleton instance
const audioManager = new AudioManager();
audioManager.init();

export default audioManager;

// Helper hook for React components
export const useAudio = () => {
    const playClick = () => audioManager.play('click');

    return {
        playClick,
        toggleAudio: () => audioManager.toggle(),
        setVolume: (vol) => audioManager.setVolume(vol),
    };
};
